# Generated by Django 5.1.7 on 2025-04-13 11:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_qrcode_image_url_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='image_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
