# Generated by Django 5.1.7 on 2025-04-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_qrcode_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
