# Generated by Django 5.1.7 on 2025-04-20 01:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_notification_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
