# Generated by Django 5.1.7 on 2025-04-20 02:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_notification_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
